### ISSUE TITLE
jamfconnect lauchagent with chrome

### ISSUE THREAD

**Issue by grainofric3** [sean-rabbitt/jamf-connect-installer-package#1]
Based on this excerpt, 

Note - Don't install the launch agent with Google.  There's no ROPG from Google
# 		as defined in the OpenID spec, so there's no ongoing password sync with the menu bar

is this still not supported on chrome, and if so, is there an alternative or workaround?
we are mostly a chrome company

thanks!

**Comment by sean-rabbitt** [comment]
Jamf Connect does not interact with the web browser. Jamf Connect synchronizes an identity provider password with a local account on a macOS client. 

To do this, the Open ID 2.0 spec allows for ROPG - basically, simple user name and password check. 

Google has not implemented ROPG. This we cannot sync a password to a local account on macOS like we can with any other provider which has correctly implemented the spec. 

Federating Google with an identity provider with full OIDC support is recommended. See the google documentation for details on how to use something like Azure to take full advantage of an identity provider.
